# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
    copyright: 2017
    project: SMS Responsive Images
    version: 1.0
    release: 1.0.1
    latex_documents:
    - - Index
        - sms_responsive_images.tex
        - SMS Responsive Images
        - sitegeist
        - manual
    latex_elements:
        papersize: a4paper
        pointsize: 10pt
        preamble: \usepackage{typo3}
    intersphinx_mapping:
        t3tsref:
        - https://docs.typo3.org/typo3cms/TyposcriptReference/
        - null
        t3start:
        - https://docs.typo3.org/typo3cms/GettingStartedTutorial/
        - null
        t3editors:
        - https://docs.typo3.org/typo3cms/EditorsTutorial/
        - null
...
